insert into carmodels (brand_id, model) values (41, 'Arkana');
insert into carmodels (brand_id, model) values (41, 'Austral');
insert into carmodels (brand_id, model) values (41, 'Captur');
insert into carmodels (brand_id, model) values (41, 'Clio');
insert into carmodels (brand_id, model) values (41, 'Espace');
insert into carmodels (brand_id, model) values (41, 'Grand Scénic');
insert into carmodels (brand_id, model) values (41, 'Kangoo');
insert into carmodels (brand_id, model) values (41, 'Koleos');
insert into carmodels (brand_id, model) values (41, 'Mégane');
insert into carmodels (brand_id, model) values (41, 'SpaceClass');
