insert into carmodels (brand_id, model) values (6, 'i4');
insert into carmodels (brand_id, model) values (6, 'i7');
insert into carmodels (brand_id, model) values (6, 'iX');
insert into carmodels (brand_id, model) values (6, 'iX1');
insert into carmodels (brand_id, model) values (6, 'iX3');
insert into carmodels (brand_id, model) values (6, 'Serie 1');
insert into carmodels (brand_id, model) values (6, 'Serie 2');
insert into carmodels (brand_id, model) values (6, 'Serie 3');
insert into carmodels (brand_id, model) values (6, 'Serie 4');
insert into carmodels (brand_id, model) values (6, 'Serie 5');
