insert into carmodels (brand_id, model) values (4, 'A1');
insert into carmodels (brand_id, model) values (4, 'A3');
insert into carmodels (brand_id, model) values (4, 'A4');
insert into carmodels (brand_id, model) values (4, 'A5');
insert into carmodels (brand_id, model) values (4, 'A6');
insert into carmodels (brand_id, model) values (4, 'A7');
insert into carmodels (brand_id, model) values (4, 'A7 Sportback');
insert into carmodels (brand_id, model) values (4, 'A8');
insert into carmodels (brand_id, model) values (4, 'e-tron GT');
insert into carmodels (brand_id, model) values (4, 'Q2');
