
insert into carmodels (model, brand_id) values ('595', 1);
insert into carmodels (model, brand_id) values ('595', 1);
insert into carmodels (model, brand_id) values ('145', 2);
insert into carmodels (model, brand_id) values ('Giulia', 2);
insert into carmodels (model, brand_id) values ('Stelvio', 2);
insert into carmodels (model, brand_id) values ('Tonale', 2);
insert into carmodels (brand_id, model) values (3, 'DB11');
insert into carmodels (brand_id, model) values (3, 'DBX');
insert into carmodels (brand_id, model) values (3, 'Vantage');
insert into carmodels (brand_id, model) values (4, 'A1');
insert into carmodels (brand_id, model) values (4, 'A3');
insert into carmodels (brand_id, model) values (4, 'A4');
insert into carmodels (brand_id, model) values (4, 'A5');
insert into carmodels (brand_id, model) values (4, 'A6');
insert into carmodels (brand_id, model) values (4, 'A7');
insert into carmodels (brand_id, model) values (4, 'A7 Sportback');
insert into carmodels (brand_id, model) values (4, 'A8');
insert into carmodels (brand_id, model) values (4, 'e-tron GT');
insert into carmodels (brand_id, model) values (4, 'Q2');
insert into carmodels (brand_id, model) values (5, 'Bentayga');
insert into carmodels (brand_id, model) values (5, 'Continental GT');
insert into carmodels (brand_id, model) values (5, 'Flying Spur');
insert into carmodels (brand_id, model) values (6, 'i4');
insert into carmodels (brand_id, model) values (6, 'i7');
insert into carmodels (brand_id, model) values (6, 'iX');
insert into carmodels (brand_id, model) values (6, 'iX1');
insert into carmodels (brand_id, model) values (6, 'iX3');
insert into carmodels (brand_id, model) values (6, 'Serie 1');
insert into carmodels (brand_id, model) values (6, 'Serie 2');
insert into carmodels (brand_id, model) values (6, 'Serie 3');
insert into carmodels (brand_id, model) values (6, 'Serie 4');
insert into carmodels (brand_id, model) values (6, 'Serie 5');
insert into carmodels (brand_id, model) values (9, 'Alero');
insert into carmodels (brand_id, model) values (9, 'Astro Van');
insert into carmodels (brand_id, model) values (9, 'Aveo');
insert into carmodels (brand_id, model) values (9, 'Blazer');
insert into carmodels (brand_id, model) values (9, 'Camaro');
insert into carmodels (brand_id, model) values (9, 'Captiva');
insert into carmodels (brand_id, model) values (9, 'Corvette');
insert into carmodels (brand_id, model) values (9, 'Epica');
insert into carmodels (brand_id, model) values (9, 'Cruze');
insert into carmodels (brand_id, model) values (9, 'Evanda');
insert into carmodels (brand_id, model) values (9, 'HHR');
insert into carmodels (brand_id, model) values (9, 'Kalos');
insert into carmodels (brand_id, model) values (9, 'Lacetti');
insert into carmodels (brand_id, model) values (9, 'Malibu');
insert into carmodels (brand_id, model) values (9, 'Matiz');
insert into carmodels (brand_id, model) values (9, 'Nubira');
insert into carmodels (brand_id, model) values (9, 'Orlando');
insert into carmodels (brand_id, model) values (9, 'Rezzo');
insert into carmodels (brand_id, model) values (9, 'Spark');
insert into carmodels (brand_id, model) values (9, 'TrailBlazer');
insert into carmodels (brand_id, model) values (10, 'Berlingo');
insert into carmodels (brand_id, model) values (10, 'C3');
insert into carmodels (brand_id, model) values (10, 'C3 Aircross');
insert into carmodels (brand_id, model) values (10, 'C4');
insert into carmodels (brand_id, model) values (10, 'C4 X');
insert into carmodels (brand_id, model) values (10, 'C5 Aircross');
insert into carmodels (brand_id, model) values (10, 'C5 X');
insert into carmodels (brand_id, model) values (10, 'SpaceTourer');
insert into carmodels (brand_id, model) values (11, 'Duster');
insert into carmodels (brand_id, model) values (11, 'Jogger');
insert into carmodels (brand_id, model) values (11, 'Sandero');
insert into carmodels (brand_id, model) values (11, 'Spring');
insert into carmodels (brand_id, model) values (12, '360');
insert into carmodels (brand_id, model) values (12, '458');
insert into carmodels (brand_id, model) values (12, '488');
insert into carmodels (brand_id, model) values (12, '550 Marnello');
insert into carmodels (brand_id, model) values (12, '599');
insert into carmodels (brand_id, model) values (12, '612');
insert into carmodels (brand_id, model) values (12, 'California');
insert into carmodels (brand_id, model) values (12, 'F430');
insert into carmodels (brand_id, model) values (15, 'Civic');
insert into carmodels (brand_id, model) values (15, 'CR-V');
insert into carmodels (brand_id, model) values (15, 'e');
insert into carmodels (brand_id, model) values (15, 'HR-V');
insert into carmodels (brand_id, model) values (15, 'Jazz');
insert into carmodels (brand_id, model) values (17, 'D-MAX');
insert into carmodels (brand_id, model) values (19, 'E-PACE');
insert into carmodels (brand_id, model) values (19, 'F-PACE');
insert into carmodels (brand_id, model) values (19, 'F-Type');
insert into carmodels (brand_id, model) values (19, 'I-PACE');
insert into carmodels (brand_id, model) values (19, 'XE');
insert into carmodels (brand_id, model) values (19, 'XF');
insert into carmodels (brand_id, model) values (20, 'Avenger');
insert into carmodels (brand_id, model) values (20, 'Compass');
insert into carmodels (brand_id, model) values (20, 'Gladiator');
insert into carmodels (brand_id, model) values (20, 'Grand Cherokee');
insert into carmodels (brand_id, model) values (20, 'Renegade');
insert into carmodels (brand_id, model) values (20, 'Wrangler');
insert into carmodels (brand_id, model) values (21, 'cee''d');
insert into carmodels (brand_id, model) values (21, 'EV6');
insert into carmodels (brand_id, model) values (21, 'Niro');
insert into carmodels (brand_id, model) values (21, 'Picanto');
insert into carmodels (brand_id, model) values (21, 'Rio');
insert into carmodels (brand_id, model) values (21, 'Sorento');
insert into carmodels (brand_id, model) values (21, 'Soul');
insert into carmodels (brand_id, model) values (21, 'Sportage');
insert into carmodels (brand_id, model) values (21, 'Stinger');
insert into carmodels (brand_id, model) values (21, 'Stonic');
insert into carmodels (brand_id, model) values (24, 'Aventador');
insert into carmodels (brand_id, model) values (24, 'Countach');
insert into carmodels (brand_id, model) values (24, 'Huracán');
insert into carmodels (brand_id, model) values (24, 'Urus');
insert into carmodels (brand_id, model) values (26, 'Defender');
insert into carmodels (brand_id, model) values (26, 'Discovery');
insert into carmodels (brand_id, model) values (26, 'Discovery Sport');
insert into carmodels (brand_id, model) values (26, 'LandRover');
insert into carmodels (brand_id, model) values (26, 'Evoque');
insert into carmodels (brand_id, model) values (26, 'Sport');
insert into carmodels (brand_id, model) values (26, 'Velar');
insert into carmodels (brand_id, model) values (28, 'ES');
insert into carmodels (brand_id, model) values (28, 'IS');
insert into carmodels (brand_id, model) values (28, 'LC');
insert into carmodels (brand_id, model) values (28, 'LS');
insert into carmodels (brand_id, model) values (28, 'NX');
insert into carmodels (brand_id, model) values (28, 'RX');
insert into carmodels (brand_id, model) values (28, 'RZ');
insert into carmodels (brand_id, model) values (28, 'UX');
insert into carmodels (brand_id, model) values (29, 'Emira');
insert into carmodels (brand_id, model) values (30, 'Ghibli');
insert into carmodels (brand_id, model) values (30, 'GranTurismo');
insert into carmodels (brand_id, model) values (30, 'Grecale');
insert into carmodels (brand_id, model) values (30, 'Levante');
insert into carmodels (brand_id, model) values (30, 'MC20');
insert into carmodels (brand_id, model) values (30, 'Quattroporte');
insert into carmodels (brand_id, model) values (31, 'CX-30');
insert into carmodels (brand_id, model) values (31, 'CX-5');
insert into carmodels (brand_id, model) values (31, 'CX-60');
insert into carmodels (brand_id, model) values (31, 'Mazda2');
insert into carmodels (brand_id, model) values (31, 'Mazda3');
insert into carmodels (brand_id, model) values (31, 'Mazda6');
insert into carmodels (brand_id, model) values (31, 'MX-30');
insert into carmodels (brand_id, model) values (31, 'MX-5');
insert into carmodels (brand_id, model) values (32, 'Citan');
insert into carmodels (brand_id, model) values (32, 'CLA');
insert into carmodels (brand_id, model) values (32, 'Clase A');
insert into carmodels (brand_id, model) values (32, 'Clase B');
insert into carmodels (brand_id, model) values (32, 'Clase C');
insert into carmodels (brand_id, model) values (32, 'Clase E');
insert into carmodels (brand_id, model) values (32, 'Clase G');
insert into carmodels (brand_id, model) values (32, 'GLC');
insert into carmodels (brand_id, model) values (32, 'GLS');
insert into carmodels (brand_id, model) values (33, '5');
insert into carmodels (brand_id, model) values (33, 'MINI');
insert into carmodels (brand_id, model) values (33, 'Cabrio');
insert into carmodels (brand_id, model) values (33, 'Clubman');
insert into carmodels (brand_id, model) values (33, 'Countryman');
insert into carmodels (brand_id, model) values (34, 'ASX');
insert into carmodels (brand_id, model) values (34, 'Eclipse Cross');
insert into carmodels (brand_id, model) values (34, 'Space Star');
insert into carmodels (brand_id, model) values (35, 'Plus');
insert into carmodels (brand_id, model) values (36, 'Ariya');
insert into carmodels (brand_id, model) values (36, 'Juke');
insert into carmodels (brand_id, model) values (36, 'LEAF');
insert into carmodels (brand_id, model) values (36, 'Micra');
insert into carmodels (brand_id, model) values (36, 'Qashqai');
insert into carmodels (brand_id, model) values (36, 'Townstar');
insert into carmodels (brand_id, model) values (36, 'X-Trail');
insert into carmodels (brand_id, model) values (37, 'Astra');
insert into carmodels (brand_id, model) values (37, 'Combo');
insert into carmodels (brand_id, model) values (37, 'Corsa');
insert into carmodels (brand_id, model) values (37, 'Crossland');
insert into carmodels (brand_id, model) values (37, 'Grandland');
insert into carmodels (brand_id, model) values (37, 'Mokka');
insert into carmodels (brand_id, model) values (37, 'Zafira');
insert into carmodels (brand_id, model) values (38, '2008');
insert into carmodels (brand_id, model) values (38, '208');
insert into carmodels (brand_id, model) values (38, '3008');
insert into carmodels (brand_id, model) values (38, '308');
insert into carmodels (brand_id, model) values (38, '408');
insert into carmodels (brand_id, model) values (38, '5008');
insert into carmodels (brand_id, model) values (38, '508');
insert into carmodels (brand_id, model) values (38, 'Rifter');
insert into carmodels (brand_id, model) values (38, 'Traveller');
insert into carmodels (brand_id, model) values (40, '718');
insert into carmodels (brand_id, model) values (40, '911');
insert into carmodels (brand_id, model) values (40, 'Cayenne');
insert into carmodels (brand_id, model) values (40, 'Macan');
insert into carmodels (brand_id, model) values (40, 'Porsche');
insert into carmodels (brand_id, model) values (40, 'Taycan');
insert into carmodels (brand_id, model) values (41, 'Arkana');
insert into carmodels (brand_id, model) values (41, 'Austral');
insert into carmodels (brand_id, model) values (41, 'Captur');
insert into carmodels (brand_id, model) values (41, 'Clio');
insert into carmodels (brand_id, model) values (41, 'Espace');
insert into carmodels (brand_id, model) values (41, 'Grand Scénic');
insert into carmodels (brand_id, model) values (41, 'Kangoo');
insert into carmodels (brand_id, model) values (41, 'Koleos');
insert into carmodels (brand_id, model) values (41, 'Mégane');
insert into carmodels (brand_id, model) values (41, 'SpaceClass');
insert into carmodels (brand_id, model) values (43, 'Arona');
insert into carmodels (brand_id, model) values (43, 'Ateca');
insert into carmodels (brand_id, model) values (43, 'Ibiza');
insert into carmodels (brand_id, model) values (43, 'León');
insert into carmodels (brand_id, model) values (43, 'Tarraco');
insert into carmodels (brand_id, model) values (44, 'Fabia');
insert into carmodels (brand_id, model) values (44, 'Kamiq');
insert into carmodels (brand_id, model) values (44, 'Karoq');
insert into carmodels (brand_id, model) values (44, 'Kodiaq');
insert into carmodels (brand_id, model) values (44, 'Octavia');
insert into carmodels (brand_id, model) values (44, 'Scala');
insert into carmodels (brand_id, model) values (44, 'Superb');
insert into carmodels (brand_id, model) values (45, 'smart');
insert into carmodels (brand_id, model) values (45, 'fortwo');
insert into carmodels (brand_id, model) values (46, 'Korando');
insert into carmodels (brand_id, model) values (46, 'Musso');
insert into carmodels (brand_id, model) values (46, 'Rexton');
insert into carmodels (brand_id, model) values (46, 'Tivoli');
insert into carmodels (brand_id, model) values (47, 'Forester');
insert into carmodels (brand_id, model) values (47, 'Impreza');
insert into carmodels (brand_id, model) values (47, 'Outback');
insert into carmodels (brand_id, model) values (47, 'Solterra');
insert into carmodels (brand_id, model) values (47, 'XV');
insert into carmodels (brand_id, model) values (48, 'Across');
insert into carmodels (brand_id, model) values (48, 'Ignis');
insert into carmodels (brand_id, model) values (48, 'S-Cross');
insert into carmodels (brand_id, model) values (48, 'Swace');
insert into carmodels (brand_id, model) values (48, 'Swift');
insert into carmodels (brand_id, model) values (48, 'Vitara');
insert into carmodels (brand_id, model) values (50, 'Model 3');
insert into carmodels (brand_id, model) values (50, 'Model S');
insert into carmodels (brand_id, model) values (50, 'Model X');
insert into carmodels (brand_id, model) values (50, 'Model Y');
insert into carmodels (model, brand_id) values ('500X', 1);
insert into carmodels (model, brand_id) values ('Doblo', 2);
insert into carmodels (model, brand_id) values ('Panda', 3);
insert into carmodels (model, brand_id) values ('Tipo', 4);
insert into carmodels (model, brand_id) values (1, 'EcoSport', 14);
insert into carmodels (model, brand_id) values (2, 'Explorer', 14);
insert into carmodels (model, brand_id) values (3, 'Fiesta', 14);
insert into carmodels (model, brand_id) values (4, 'Focus', 14);
insert into carmodels (model, brand_id) values (5, 'Grand', 14);
insert into carmodels (model, brand_id) values (6, 'Tourneo', 14);
insert into carmodels (model, brand_id) values (7, 'Connect', 14);
insert into carmodels (model, brand_id) values (8, 'Kuga', 14);
insert into carmodels (model, brand_id) values (9, 'Mustang', 14);
